# Generated by Django 3.2.16 on 2022-11-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_ID', models.CharField(max_length=200)),
                ('program_date', models.DateField()),
                ('program_data', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Program data',
                'unique_together': {('program_ID', 'program_date')},
            },
        ),
    ]
