# Generated by Django 3.2.16 on 2022-11-15 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProgramItem',
        ),
    ]
