# Generated by Django 3.2.16 on 2022-11-24 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annoucement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annoucement',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
